spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_dispatch
    username: delivery_dispatch
    password: delivery_dispatch
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
